{
  "openapi": "3.0.0",
  "info": {
    "title": "ResourceFeedback",
    "description": "        <p>The ResourceFeedback resource lets your app report the status of shops and their resources. For example, if\n        your app is a marketplace channel, then you can use resource feedback to alert merchants that they need to connect their marketplace account by signing in.</p>\n\n        <p>Resource feedback notifications are displayed to the merchant on the home screen of their Shopify admin, and in the product details view for any products that are published to your app.</p>\n\n        <p>This resource should be used only in cases where you're describing steps that a merchant is required to complete. If your app offers optional or promotional set-up steps, or if it makes recommendations, then don't use resource feedback to let merchants know about them.</p>\n\n        <h2>Sending feedback on a shop</h2>\n\n        <p>You can send resource feedback on a shop to let the merchant know what steps they need to take to make sure that your app is set up correctly. Feedback can have one of two states: <code>requires_action</code> or <code>success</code>. You need to send a <code>requires_action</code> feedback request for each step that the merchant is required to complete.</p>\n\n        <p>If there are multiple set-up steps that require merchant action, then send feedback with a state of <code>requires_action</code> as merchants complete prior steps. And to remove the feedback message from the Shopify admin, send a <code>success</code> feedback request.</p>\n\n        <div class=\"note\">\n          <h4>Important</h4>\n          <p>Sending feedback replaces previously sent feedback for the Shop. Unlike REST-style APIs, you don't need to make a PATCH or PUT request to update any previously sent feedback. Send a new POST request to push the latest state of a shop or its resources to Shopify.</p>\n        </div>\n\n        <h2>Formatting the resource feedback message field</h2>\n\n        <p>If the feedback state is <code>requires_action</code>, then you can send a string message that communicates the action to be taken by the merchant.</p>\n        <p>The string must be a single message up to 100 characters long and must end with a period.\n        You need to adhere to the message formatting rules or your requests will fail:</p>\n\n        <li><code>[Explanation of the problem]. [Suggested action].</code></li>\n        <br>\n        <p><strong>Examples:</strong></p>\n        <li><code>[Your app name]</code> is not connected. Connect your account to use this sales channel. <code>[Learn more]</code></li>\n        <li><code>[Your app name]</code> is not configured. Agree to the terms and conditions to use this app. <code>[Learn more]</code></li>\n        <br>\n        <p>Both <code>Your app name</code> and <code>Learn more</code> (a button which directs merchants to your app) are automatically populated in the Shopify admin.</p>\n\n        <h2>Setting feedback permissions</h2>\n        <p>Add the <code>write_resource_feedbacks</code> permission to your <a href=\"/docs/admin-api/access-scopes\">requested scopes</a>.</p>\n",
    "x-owner": "https://vault.shopify.io/teams/2386",
    "x-description-list": null,
    "version": "2022-10",
    "show-privacy-note": true
  },
  "paths": [
    {
      "description": "Creates shop resource feedback.",
      "summary": "Create a new ResourceFeedback",
      "operationId": "CreateanewResourceFeedback",
      "parameters": [
        {
          "name": "api_version",
          "in": "path",
          "schema": {
            "type": "string"
          },
          "required": true
        },
        {
          "name": "feedback_generated_at",
          "description": "An ISO 8601 date and time indicating when the feedback was generated by your app.",
          "in": "query",
          "schema": {
            "type": "string"
          },
          "required": true
        },
        {
          "name": "messages",
          "description": "An array containing a single message.\nSee <a href=\"#formatting-the-resource-feedback-field-{{ current_version }}\">\n<em>Formatting the resource feedback message field</em></a> for formatting requirements.\n",
          "in": "query",
          "schema": {
            "type": "string"
          },
          "required": true
        },
        {
          "name": "state",
          "description": "Must be one of the following values:",
          "in": "query",
          "schema": {
            "type": "string"
          },
          "required": true,
          "examples": {
            "requires_action": {
              "summary": "Indicates that your app requires the merchant to resolve an issue with their shop.",
              "value": "requires_action"
            },
            "success": {
              "summary": "Indicates that the app does not have any outstanding issues with this shop.",
              "value": "success"
            }
          }
        }
      ],
      "responses": {
        "202": {
          "description": "Create a new ResourceFeedback",
          "content": {
            "application/json": {
              "examples": {
                "Create a shop feedback record indicating a problem specific to your app": {
                  "value": {
                    "resource_feedback": {
                      "created_at": "2023-01-03T10:53:47-07:00",
                      "updated_at": "2023-01-03T10:53:47-07:00",
                      "resource_id": 548380009,
                      "resource_type": "Shop",
                      "resource_updated_at": null,
                      "messages": [
                        "is not connected. Connect your account to use this sales channel."
                      ],
                      "feedback_generated_at": "2023-01-03T10:53:46-07:00",
                      "state": "requires_action"
                    }
                  }
                },
                "Create a shop feedback record indicating the Shop is usable by your app": {
                  "value": {
                    "resource_feedback": {
                      "created_at": "2023-01-03T10:53:50-07:00",
                      "updated_at": "2023-01-03T10:53:50-07:00",
                      "resource_id": 548380009,
                      "resource_type": "Shop",
                      "resource_updated_at": null,
                      "messages": [],
                      "feedback_generated_at": "2023-01-03T10:53:49-07:00",
                      "state": "success"
                    }
                  }
                }
              }
            }
          }
        },
        "422": {
          "description": "Create a new ResourceFeedback",
          "content": {
            "application/json": {
              "examples": {
                "Sending an invalid feedback payload returns an error": {
                  "value": {
                    "errors": {
                      "messages": [
                        "State must be one of success and requires_action"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "409": {
          "description": "Create a new ResourceFeedback",
          "content": {
            "application/json": {
              "examples": {
                "Sending outdated feedback (previous feedback\n        payload has a greater resource_updated_at value) returns an error": {
                  "value": {
                    "errors": {
                      "messages": [
                        "Feedback request not delivered. Feedback request is older than a previously delivered feedback request."
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "x-examples": [
        {
          "status": "202",
          "request_query": "",
          "request_path": "/admin/api/2022-10/resource_feedback.json",
          "request_method": "POST",
          "request": {
            "action": "POST /admin/api/unstable/resource_feedback.json",
            "headers": {},
            "body": "{\"resource_feedback\":{\"state\":\"requires_action\",\"messages\":[\"is not connected. Connect your account to use this sales channel.\"],\"feedback_generated_at\":\"2023-01-03T17:53:46.212756Z\"}}"
          },
          "response": {
            "action": "HTTP/1.1 202 Accepted",
            "headers": {},
            "body": "{\"resource_feedback\":{\"created_at\":\"2023-01-03T12:53:47-05:00\",\"updated_at\":\"2023-01-03T12:53:47-05:00\",\"resource_id\":548380009,\"resource_type\":\"Shop\",\"resource_updated_at\":null,\"messages\":[\"is not connected. Connect your account to use this sales channel.\"],\"feedback_generated_at\":\"2023-01-03T12:53:46-05:00\",\"state\":\"requires_action\"}}"
          },
          "name": "Create a shop feedback record indicating a problem specific to your app",
          "codeSamples": [
            {
              "language": "curl",
              "example_code": "curl -d '{\"resource_feedback\":{\"state\":\"requires_action\",\"messages\":[\"is not connected. Connect your account to use this sales channel.\"],\"feedback_generated_at\":\"2023-01-03T17:53:46.212756Z\"}}' \\\n-X POST \"https://your-development-store.myshopify.com/admin/api/2022-10/resource_feedback.json\" \\\n-H \"X-Shopify-Access-Token: {access_token}\" \\\n-H \"Content-Type: application/json\"\n"
            },
            {
              "language": "ruby",
              "example_code": "test_session = ShopifyAPI::Utils::SessionUtils.load_current_session(\n  auth_header: request.auth_header,\n  cookies: request.cookies,\n)\n\nresource_feedback = ShopifyAPI::ResourceFeedback.new(session: test_session)\nresource_feedback.state = \"requires_action\"\nresource_feedback.messages = [\n  \"is not connected. Connect your account to use this sales channel.\"\n]\nresource_feedback.feedback_generated_at = \"2023-01-03T17:53:46.212756Z\"\nresource_feedback.save!"
            },
            {
              "language": "node",
              "example_code": "// Session is built by the OAuth process\n\nconst resource_feedback = new shopify.rest.ResourceFeedback({session: session});\nresource_feedback.state = \"requires_action\";\nresource_feedback.messages = [\n  \"is not connected. Connect your account to use this sales channel.\"\n];\nresource_feedback.feedback_generated_at = \"2023-01-03T17:53:46.212756Z\";\nawait resource_feedback.save({\n  update: true,\n});"
            },
            {
              "language": "php",
              "example_code": "use Shopify\\Rest\\Admin2022_10\\ResourceFeedback;\nuse Shopify\\Utils;\n\n$this->test_session = Utils::loadCurrentSession(\n    $requestHeaders,\n    $requestCookies,\n    $isOnline\n);\n\n$resource_feedback = new ResourceFeedback($this->test_session);\n$resource_feedback->state = \"requires_action\";\n$resource_feedback->messages = [\n    \"is not connected. Connect your account to use this sales channel.\"\n];\n$resource_feedback->feedback_generated_at = \"2023-01-03T17:53:46.212756Z\";\n$resource_feedback->save(\n    true, // Update Object\n);"
            }
          ]
        },
        {
          "status": "202",
          "request_query": "",
          "request_path": "/admin/api/2022-10/resource_feedback.json",
          "request_method": "POST",
          "request": {
            "action": "POST /admin/api/unstable/resource_feedback.json",
            "headers": {},
            "body": "{\"resource_feedback\":{\"state\":\"success\",\"feedback_generated_at\":\"2023-01-03T17:53:49.185362Z\"}}"
          },
          "response": {
            "action": "HTTP/1.1 202 Accepted",
            "headers": {},
            "body": "{\"resource_feedback\":{\"created_at\":\"2023-01-03T12:53:50-05:00\",\"updated_at\":\"2023-01-03T12:53:50-05:00\",\"resource_id\":548380009,\"resource_type\":\"Shop\",\"resource_updated_at\":null,\"messages\":[],\"feedback_generated_at\":\"2023-01-03T12:53:49-05:00\",\"state\":\"success\"}}"
          },
          "name": "Create a shop feedback record indicating the Shop is usable by your app",
          "codeSamples": [
            {
              "language": "curl",
              "example_code": "curl -d '{\"resource_feedback\":{\"state\":\"success\",\"feedback_generated_at\":\"2023-01-03T17:53:49.185362Z\"}}' \\\n-X POST \"https://your-development-store.myshopify.com/admin/api/2022-10/resource_feedback.json\" \\\n-H \"X-Shopify-Access-Token: {access_token}\" \\\n-H \"Content-Type: application/json\"\n"
            },
            {
              "language": "ruby",
              "example_code": "test_session = ShopifyAPI::Utils::SessionUtils.load_current_session(\n  auth_header: request.auth_header,\n  cookies: request.cookies,\n)\n\nresource_feedback = ShopifyAPI::ResourceFeedback.new(session: test_session)\nresource_feedback.state = \"success\"\nresource_feedback.feedback_generated_at = \"2023-01-03T17:53:49.185362Z\"\nresource_feedback.save!"
            },
            {
              "language": "node",
              "example_code": "// Session is built by the OAuth process\n\nconst resource_feedback = new shopify.rest.ResourceFeedback({session: session});\nresource_feedback.state = \"success\";\nresource_feedback.feedback_generated_at = \"2023-01-03T17:53:49.185362Z\";\nawait resource_feedback.save({\n  update: true,\n});"
            },
            {
              "language": "php",
              "example_code": "use Shopify\\Rest\\Admin2022_10\\ResourceFeedback;\nuse Shopify\\Utils;\n\n$this->test_session = Utils::loadCurrentSession(\n    $requestHeaders,\n    $requestCookies,\n    $isOnline\n);\n\n$resource_feedback = new ResourceFeedback($this->test_session);\n$resource_feedback->state = \"success\";\n$resource_feedback->feedback_generated_at = \"2023-01-03T17:53:49.185362Z\";\n$resource_feedback->save(\n    true, // Update Object\n);"
            }
          ]
        },
        {
          "status": "422",
          "request_query": "",
          "request_path": "/admin/api/2022-10/resource_feedback.json",
          "request_method": "POST",
          "request": {
            "action": "POST /admin/api/unstable/resource_feedback.json",
            "headers": {},
            "body": "{\"resource_feedback\":{\"state\":\"foobar\",\"feedback_generated_at\":\"2023-01-03T17:53:43.192491Z\"}}"
          },
          "response": {
            "action": "HTTP/1.1 422 Unprocessable Entity",
            "headers": {},
            "body": "{\"errors\":{\"messages\":[\"State must be one of success and requires_action\"]}}"
          },
          "name": "Sending an invalid feedback payload returns an error",
          "codeSamples": [
            {
              "language": "curl",
              "example_code": "curl -d '{\"resource_feedback\":{\"state\":\"foobar\",\"feedback_generated_at\":\"2023-01-03T17:53:43.192491Z\"}}' \\\n-X POST \"https://your-development-store.myshopify.com/admin/api/2022-10/resource_feedback.json\" \\\n-H \"X-Shopify-Access-Token: {access_token}\" \\\n-H \"Content-Type: application/json\"\n"
            },
            {
              "language": "ruby",
              "example_code": "test_session = ShopifyAPI::Utils::SessionUtils.load_current_session(\n  auth_header: request.auth_header,\n  cookies: request.cookies,\n)\n\nresource_feedback = ShopifyAPI::ResourceFeedback.new(session: test_session)\nresource_feedback.state = \"foobar\"\nresource_feedback.feedback_generated_at = \"2023-01-03T17:53:43.192491Z\"\nresource_feedback.save!"
            },
            {
              "language": "node",
              "example_code": "// Session is built by the OAuth process\n\nconst resource_feedback = new shopify.rest.ResourceFeedback({session: session});\nresource_feedback.state = \"foobar\";\nresource_feedback.feedback_generated_at = \"2023-01-03T17:53:43.192491Z\";\nawait resource_feedback.save({\n  update: true,\n});"
            },
            {
              "language": "php",
              "example_code": "use Shopify\\Rest\\Admin2022_10\\ResourceFeedback;\nuse Shopify\\Utils;\n\n$this->test_session = Utils::loadCurrentSession(\n    $requestHeaders,\n    $requestCookies,\n    $isOnline\n);\n\n$resource_feedback = new ResourceFeedback($this->test_session);\n$resource_feedback->state = \"foobar\";\n$resource_feedback->feedback_generated_at = \"2023-01-03T17:53:43.192491Z\";\n$resource_feedback->save(\n    true, // Update Object\n);"
            }
          ]
        },
        {
          "status": "409",
          "request_query": "",
          "request_path": "/admin/api/2022-10/resource_feedback.json",
          "request_method": "POST",
          "request": {
            "action": "POST /admin/api/unstable/resource_feedback.json",
            "headers": {},
            "body": "{\"resource_feedback\":{\"state\":\"success\",\"feedback_generated_at\":\"2023-01-03T17:53:47.699868Z\"}}"
          },
          "response": {
            "action": "HTTP/1.1 409 Conflict",
            "headers": {},
            "body": "{\"errors\":{\"messages\":[\"Feedback request not delivered. Feedback request is older than a previously delivered feedback request.\"]}}"
          },
          "name": "Sending outdated feedback (previous feedback\n        payload has a greater resource_updated_at value) returns an error",
          "codeSamples": [
            {
              "language": "curl",
              "example_code": "curl -d '{\"resource_feedback\":{\"state\":\"success\",\"feedback_generated_at\":\"2023-01-03T17:53:47.699868Z\"}}' \\\n-X POST \"https://your-development-store.myshopify.com/admin/api/2022-10/resource_feedback.json\" \\\n-H \"X-Shopify-Access-Token: {access_token}\" \\\n-H \"Content-Type: application/json\"\n"
            },
            {
              "language": "ruby",
              "example_code": "test_session = ShopifyAPI::Utils::SessionUtils.load_current_session(\n  auth_header: request.auth_header,\n  cookies: request.cookies,\n)\n\nresource_feedback = ShopifyAPI::ResourceFeedback.new(session: test_session)\nresource_feedback.state = \"success\"\nresource_feedback.feedback_generated_at = \"2023-01-03T17:53:47.699868Z\"\nresource_feedback.save!"
            },
            {
              "language": "node",
              "example_code": "// Session is built by the OAuth process\n\nconst resource_feedback = new shopify.rest.ResourceFeedback({session: session});\nresource_feedback.state = \"success\";\nresource_feedback.feedback_generated_at = \"2023-01-03T17:53:47.699868Z\";\nawait resource_feedback.save({\n  update: true,\n});"
            },
            {
              "language": "php",
              "example_code": "use Shopify\\Rest\\Admin2022_10\\ResourceFeedback;\nuse Shopify\\Utils;\n\n$this->test_session = Utils::loadCurrentSession(\n    $requestHeaders,\n    $requestCookies,\n    $isOnline\n);\n\n$resource_feedback = new ResourceFeedback($this->test_session);\n$resource_feedback->state = \"success\";\n$resource_feedback->feedback_generated_at = \"2023-01-03T17:53:47.699868Z\";\n$resource_feedback->save(\n    true, // Update Object\n);"
            }
          ]
        }
      ],
      "x-api-accessibilities": {
        "initial": [
          {
            "scope": "resource_feedbacks"
          }
        ]
      },
      "url": "/admin/api/{api_version}/resource_feedback.json",
      "action": "post"
    },
    {
      "description": "Returns a list (zero or one) of resource feedback objects.\n          <div class=\"note\">\n            <h4>Important</h4>\n            <p>Note that ids are not returned as part of this request. Records are immutable except when POST replaces them.</p>\n          </div>",
      "summary": "Receive a list of all ResourceFeedbacks",
      "operationId": "ReceivealistofallResourceFeedbacks",
      "parameters": [
        {
          "name": "api_version",
          "in": "path",
          "schema": {
            "type": "string"
          },
          "required": true
        }
      ],
      "responses": {
        "200": {
          "description": "Receive a list of all ResourceFeedbacks",
          "content": {
            "application/json": {
              "examples": {
                "Get a list of resource feedback records for a specific shop": {
                  "value": {
                    "resource_feedback": [
                      {
                        "created_at": "2023-01-03T10:53:44-07:00",
                        "updated_at": "2023-01-03T10:53:44-07:00",
                        "resource_id": 548380009,
                        "resource_type": "Shop",
                        "resource_updated_at": null,
                        "messages": [
                          "is not connected. Connect your account to use this sales channel."
                        ],
                        "feedback_generated_at": "2023-01-03T09:53:44-07:00",
                        "state": "requires_action"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "x-examples": [
        {
          "status": "200",
          "request_query": "",
          "request_path": "/admin/api/2022-10/resource_feedback.json",
          "request_method": "GET",
          "request": {
            "action": "GET /admin/api/unstable/resource_feedback.json",
            "headers": {},
            "body": ""
          },
          "response": {
            "action": "HTTP/1.1 200 OK",
            "headers": {},
            "body": "{\"resource_feedback\":[{\"created_at\":\"2023-01-03T12:53:44-05:00\",\"updated_at\":\"2023-01-03T12:53:44-05:00\",\"resource_id\":548380009,\"resource_type\":\"Shop\",\"resource_updated_at\":null,\"messages\":[\"is not connected. Connect your account to use this sales channel.\"],\"feedback_generated_at\":\"2023-01-03T11:53:44-05:00\",\"state\":\"requires_action\"}]}"
          },
          "name": "Get a list of resource feedback records for a specific shop",
          "codeSamples": [
            {
              "language": "curl",
              "example_code": "curl -X GET \"https://your-development-store.myshopify.com/admin/api/2022-10/resource_feedback.json\" \\\n-H \"X-Shopify-Access-Token: {access_token}\"\n"
            },
            {
              "language": "ruby",
              "example_code": "test_session = ShopifyAPI::Utils::SessionUtils.load_current_session(\n  auth_header: request.auth_header,\n  cookies: request.cookies,\n)\n\nShopifyAPI::ResourceFeedback.all(\n  session: test_session,\n)"
            },
            {
              "language": "node",
              "example_code": "// Session is built by the OAuth process\n\nawait shopify.rest.ResourceFeedback.all({\n  session: session,\n});"
            },
            {
              "language": "php",
              "example_code": "use Shopify\\Rest\\Admin2022_10\\ResourceFeedback;\nuse Shopify\\Utils;\n\n$this->test_session = Utils::loadCurrentSession(\n    $requestHeaders,\n    $requestCookies,\n    $isOnline\n);\n\nResourceFeedback::all(\n    $this->test_session, // Session\n    [], // Url Ids\n    [], // Params\n);"
            }
          ]
        }
      ],
      "x-api-accessibilities": {
        "initial": [
          {
            "scope": "resource_feedbacks"
          }
        ]
      },
      "url": "/admin/api/{api_version}/resource_feedback.json",
      "action": "get"
    }
  ],
  "components": [
    {
      "name": "ResourceFeedback",
      "title": "ResourceFeedback",
      "type": "object",
      "properties": [
        {
          "description": "          DateTime when the resource feedback record was stored by Shopify.\n          <strong>Type:</strong> ISO 8601 UTC DateTime as string with year, month (or week), day, hour, minute, second, time zone.\n",
          "type": "string",
          "readOnly": true,
          "example": "2023-01-03 17:05:08 UTC",
          "name": "created_at"
        },
        {
          "description": "          DateTime when the resource feedback record was last updated by Shopify.\n          <strong>Type:</strong> ISO 8601 UTC DateTime as string with year, month (or week), day, hour, minute, second, time zone.\n",
          "type": "string",
          "readOnly": true,
          "example": "2023-01-03 17:05:08 UTC",
          "name": "updated_at"
        },
        {
          "description": "          Unique id of the resource.\n",
          "type": "string",
          "readOnly": true,
          "example": 321,
          "name": "resource_id"
        },
        {
          "description": "          Type of resource for which feedback is returned. eg. Shop, Product.\n",
          "type": "string",
          "readOnly": true,
          "example": "Shop",
          "name": "resource_type"
        },
        {
          "description": "          Indicates the state that the Shop or resource is in, from the perspective of your app. Valid values are <code>requires_action</code>, or <code>success</code>.\n",
          "type": "string",
          "example": "requires_action",
          "name": "state"
        },
        {
          "description": "          <p>\n            A concise set of copy strings to be displayed to merchants, to guide them in resolving problems your app\n            encounters when trying to make use of their Shop and its resources.\n          </p>\n\n          <p>\n            Required only when state is <code>requires_action</code>. Disallowed when state is <code>success</code>.\n          </p>\n\n          <p>\n            <strong>Content restrictions for Shop feedback:</strong>\n            one message up to 100 characters long.\n          </p>\n",
          "type": "string",
          "example": [
            "is not connected. Connect your account to use this sales channel."
          ],
          "name": "messages"
        },
        {
          "description": "          <p>\n            The time at which the payload is constructed. Used to help determine whether incoming feedback is\n            outdated compared to feedback already received, and if it should be ignored upon arrival.\n            <strong>Type:</strong> ISO 8601 UTC datetime as string\n            with year, month [or week], day, hour, minute, second, millisecond, and time zone.\n          </p>\n\n          <div class=\"note\">\n            <h4>Note</h4>\n            <p>If you queue a Feedback API payload for delivery at a later time, do not update this value\n            when the API call is actually made; ensure that the current time is set when building the payload.</p>\n          </div>\n",
          "type": "string",
          "example": "2023-01-03T17:05:08.126204Z",
          "name": "feedback_generated_at"
        }
      ],
      "required": null
    }
  ],
  "x-shopify-meta": {
    "channels": false,
    "file_name": "sales-channels/resourcefeedback",
    "gid": "035f4f82-356c-435c-8ef4-1c75d7822ab4",
    "glossary": false,
    "hidden": false,
    "legacy-urls": [
      "/api/reference/resourcefeedback",
      "/api/reference/sales_channels/resourcefeedback"
    ],
    "meta_description": "Notify merchants about actions required to resolve errors with your app.",
    "postman_group": "Sales channels",
    "keywords": [
      "api"
    ],
    "api_versioning": true,
    "shopify_plus": false,
    "weight": null,
    "usage-notes": null
  },
  "personal_data_fields": []
}